spring.application.name=wedding-backend

spring.datasource.url=${DB_URL:jdbc:h2:file:./data/wedding_invitation;MODE=MySQL;DATABASE_TO_LOWER=TRUE}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.web.error.include-message=never

spring.security.user.name=${ADMIN_USERNAME}
spring.security.user.password=${ADMIN_PASSWORD}

spring.h2.console.enabled=${H2_CONSOLE_ENABLED:false}
spring.h2.console.path=/h2-console